#!/usr/bin/env bash

while true; do
	inotifywait -q -e close_write,moved_to,create src/jquery.scrollajax.js Makefile > /dev/null
	echo -n "[`date +'%Y-%m-%d %H:%M:%S'`] Rebuilding... "
	make > /dev/null
	echo "done !"
done
